### ISSUE TITLE
Bug with the emulator button

### ISSUE THREAD

**Issue by sDetective** [ethanaobrien/emulator-button#6]
this seems to happen on both Chromebook and windows 
[raw.githack.com-1664198681229.log](https://github.com/EmulatorJS/emulator-button/files/9646568/raw.githack.com-1664198681229.log)
heres the log

**Comment by ethanaobrien** [comment]
This was fixed in the most recent update. Clear your cache and your cookies

**Comment by sDetective** [comment]
it still does this through even if the cache and cookies are cleared, it's just blank and doesn't respond whenever I would click load game which usually tells you what core to pick then uploads the game but it doesn't it just goes to this blank black screen
![Screenshot 2022-09-26 9 32 22 AM](https://user-images.githubusercontent.com/85586892/192303528-ea9430da-e558-461e-9579-dcdeacc6df41.png)

**Comment by ethanaobrien** [comment]
As I said, clear your cache and your cookies, I checked and can no longer reproduce this issue. Try the button on a website you've never used before, that might work.

**Comment by sDetective** [comment]
Idk what you mean by use the button on a website like google site or something

**Comment by sDetective** [comment]
omg I just now figure it out im sorry about the hassel I had no idea it worked that way

**Comment by ethanaobrien** [comment]
No problem!

**Comment by sDetective** [comment]
Does the PlayStation core usually work well cause it seems to not work as expected something with missing assets and updating drivers also boots me to the retroarch menu I've tried it with resident evil 3 which worked really well before, do I sure the log for this issue?

**Comment by ethanaobrien** [comment]
Check the use old core option box. The new PlayStation core does not support the same rom types

**Comment by sDetective** [comment]
What types are there?

**Comment by ethanaobrien** [comment]
I don't have them memorized read the docs on the website

**Comment by sDetective** [comment]
On liberto?

**Comment by ethanaobrien** [comment]
No, the emulatorjs website, mentioned in the readme of the emulatorjs repo

**Comment by sDetective** [comment]
oh ok
