### ISSUE TITLE
this stopped working

### ISSUE THREAD

**Issue by CHARLYCHEB** [ethanaobrien/emulator-button#8]
it says "looks like githack is down or you are offline. Please try again later." and im not offline

**Comment by ethanaobrien** [comment]
Probably happened with 4.0. I'll try to look at this tomorrow

**Comment by CHARLYCHEB** [comment]
nevermind it was probably just when you were upadating

**Comment by ethanaobrien** [comment]
Sorry, I resolved this issue and forgot to let you know it was fixed. I recently fixed this issue
