### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Charlycheb2** [ethanaobrien/emulator-button#9]
You might just be updating it, but as of now it is no longer working.

**Comment by ethanaobrien** [comment]
Some description would be nice

**Comment by Charlycheb2** [comment]
> Some description would be nice

[Screen recording 2024-01-29 11.08.28 AM.webm](https://github.com/EmulatorJS/emulator-button/assets/152919946/9f6f2254-b6e2-457e-9635-8ab81834d9ba)
this is what happens with all files
[Screen recording 2024-01-29 11.08.28 AM.webm](https://github.com/EmulatorJS/emulator-button/assets/152919946/2139b5e7-8e78-4889-a6cb-11798813288f)
